version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: blog_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kn5624
      POSTGRES_DB: blog_production_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_production_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: blog_node_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_PASS=kn5624
      - DB_NAME=blog_production_db
      - DB_HOST=db
      - JWT_SECRET=chave_mestra_ultra_secreta_smartnx_2026
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: